export const locations: string[] = [
  "Plaza Mayor de Nuevo Chimbote",
  "Municipalidad Distrital de Nuevo Chimbote",
  "Catedral Nuestra Señora del Carmen y San Pedro Apóstol",
  "Óvalo de la Familia",
  "Playa Atahualpa",
  "Malecón Grau",
  "I.E. Inmaculada de la Merced",
  "Urbanización Bellamar",
  "Urbanización Los Héroes",
  "Urbanización Casuarinas",
  "Urbanización Nicolás Garatea",
  "Urbanización El Pacífico",
  "Urbanización La Caleta",
  "Urbanización Santa Rosa",
  "Urbanización Villa María",
  "3 de Octubre",
  "Villa Hermosa",
  "Teresa de Calcuta",
  "Los Constructores",
  "Los Jardines",
  "El Acuario",
  "15 de Abril",
  "Las Delicias",
  "Parque Industrial 27 de Octubre",
  "Parque Industrial El Satélite",
  "Mercado Buenos Aires",
  "Universidad Nacional del Santa (UNS)",
  "Universidad San Pedro",
  "Instituto Superior Tecnológico Carlos Salazar Romero",
  "CETPRO Nuevo Chimbote",
  "Hospital Regional Eleazar Guzmán Barrón",
  "Centro de Salud Buenos Aires",
  "Centro de Salud Villa María",
  "Clínicas Particulares (varias)",
  "Playa El Dorado",
  "Playa Los Pescadores",
  "Parque 21 de Abril",
  "Complejo Deportivo Casuarinas",
  "Vía de Evitamiento",
  "Av. Pacífico",
  "Av. Anchoveta",
  "Av. José Pardo",
  "Comisaría Buenos Aires",
  "Comisaría Villa María",
  "SEDACHIMBOTE (Planta de Agua)",
  "SERENAZGO Nuevo Chimbote",
  "Estadio Centenario",
];
