export const locations: string[] = [
  "Centro Urbano / Plaza Mayor de Nuevo Chimbote",
  "Centro Urbano / Municipalidad Distrital de Nuevo Chimbote",
  "Centro Urbano / Catedral Nuestra Señora del Carmen y San Pedro Apóstol",
  "Centro Urbano / Óvalo de la Familia",
  "Urbanización Buenos Aires / Playa Atahualpa",
  "Urbanización Buenos Aires / Malecón Grau",
  "Urbanización Buenos Aires / I.E. Inmaculada de la Merced",
  "Urbanización Bellamar",
  "Urbanización Los Héroes",
  "Urbanización Casuarinas",
  "Urbanización Nicolás Garatea",
  "Urbanización El Pacífico",
  "Urbanización La Caleta",
  "Urbanización Santa Rosa",
  "Urbanización Villa María",
  "AA.HH. / 3 de Octubre",
  "AA.HH. / Villa Hermosa",
  "AA.HH. / Teresa de Calcuta",
  "AA.HH. / Los Constructores",
  "AA.HH. / Los Jardines",
  "AA.HH. / El Acuario",
  "AA.HH. / 15 de Abril",
  "AA.HH. / Las Delicias",
  "Zonas Industriales y Comerciales / Parque Industrial 27 de Octubre",
  "Zonas Industriales y Comerciales / Parque Industrial El Satélite",
  "Zonas Industriales y Comerciales / Mercado Buenos Aires",
  "Educación y Universidades / Universidad Nacional del Santa (UNS)",
  "Educación y Universidades / Universidad San Pedro",
  "Educación y Universidades / Instituto Superior Tecnológico Carlos Salazar Romero",
  "Educación y Universidades / CETPRO Nuevo Chimbote",
  "Salud / Hospital Regional Eleazar Guzmán Barrón",
  "Salud / Centro de Salud Buenos Aires",
  "Salud / Centro de Salud Villa María",
  "Salud / Clínicas Particulares (varias)",
  "Playas y Recreación / Playa Atahualpa",
  "Playas y Recreación / Playa El Dorado",
  "Playas y Recreación / Playa Los Pescadores",
  "Playas y Recreación / Parque 21 de Abril",
  "Playas y Recreación / Complejo Deportivo Casuarinas",
  "Transporte y Accesos / Óvalo La Familia",
  "Transporte y Accesos / Vía de Evitamiento",
  "Transporte y Accesos / Av. Pacífico",
  "Transporte y Accesos / Av. Anchoveta",
  "Transporte y Accesos / Av. José Pardo",
  "Instituciones y Servicios Públicos / Comisaría Buenos Aires",
  "Instituciones y Servicios Públicos / Comisaría Villa María",
  "Instituciones y Servicios Públicos / SEDACHIMBOTE (Planta de Agua)",
  "Instituciones y Servicios Públicos / SERENAZGO Nuevo Chimbote",
  "Instituciones y Servicios Públicos / Estadio Centenario",
];